import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";

interface SubjectEntry {
  id: string;
  date: string;
  subject: string;
  platform: string;
  topics: string;
  duration: string;
}

interface PDFRequest {
  childName: string;
  reportType: "daily" | "weekly";
  subjects: SubjectEntry[];
  notes: string;
  reportContent: string;
  generatedDate: string;
}

export async function POST(req: NextRequest) {
  try {
    const body: PDFRequest = await req.json();

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    let yPos = 20;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;

    // Header
    pdf.setFontSize(24);
    pdf.setTextColor(0, 102, 204); // primary color
    pdf.text("Learning Progress Report", margin, yPos);

    yPos += 15;
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Student: ${body.childName}`, margin, yPos);
    yPos += 6;
    pdf.text(`Date: ${body.generatedDate}`, margin, yPos);

    yPos += 12;
    pdf.setDrawColor(0, 102, 204);
    pdf.line(margin, yPos, pageWidth - margin, yPos);

    yPos += 8;

    // Activities Section
    pdf.setFontSize(14);
    pdf.setTextColor(26, 26, 46);
    pdf.text(body.reportType === "weekly" ? "Learning by Day" : "Learning Activities", margin, yPos);

    yPos += 10;
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);

    if (body.reportType === "weekly") {
      const byDate: { [key: string]: SubjectEntry[] } = {};
      body.subjects.forEach((subject) => {
        if (!byDate[subject.date]) byDate[subject.date] = [];
        byDate[subject.date].push(subject);
      });

      Object.keys(byDate)
        .sort()
        .forEach((date) => {
          const dateObj = new Date(date);
          const dayName = dateObj.toLocaleDateString("en-US", { weekday: "long" });
          const formattedDate = dateObj.toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
          });

          if (yPos > 250) {
            pdf.addPage();
            yPos = 20;
          }

          pdf.setTextColor(0, 102, 204);
          pdf.setFont("helvetica", "bold");
          pdf.text(`${dayName}, ${formattedDate}`, margin + 2, yPos);
          yPos += 6;

          byDate[date].forEach((subject) => {
            if (yPos > 270) {
              pdf.addPage();
              yPos = 20;
            }

            pdf.setTextColor(26, 26, 46);
            pdf.setFont("helvetica", "bold");
            pdf.text(`• ${subject.subject}`, margin + 5, yPos);
            yPos += 5;

            pdf.setTextColor(100, 100, 100);
            pdf.setFont("helvetica", "normal");
            pdf.text(`Platform: ${subject.platform} | Duration: ${subject.duration} min`, margin + 8, yPos);
            yPos += 5;
            pdf.text(`Topics: ${subject.topics}`, margin + 8, yPos);
            yPos += 6;
          });
        });
    } else {
      body.subjects.forEach((subject) => {
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
        }

        pdf.setTextColor(26, 26, 46);
        pdf.setFont("helvetica", "bold");
        pdf.text(`• ${subject.subject}`, margin + 5, yPos);
        yPos += 5;

        pdf.setTextColor(100, 100, 100);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Platform: ${subject.platform} | Duration: ${subject.duration} min`, margin + 8, yPos);
        yPos += 5;
        pdf.text(`Topics: ${subject.topics}`, margin + 8, yPos);
        yPos += 6;
      });
    }

    yPos += 8;

    // Assessment Section
    if (yPos > 250) {
      pdf.addPage();
      yPos = 20;
    }

    pdf.setFontSize(14);
    pdf.setTextColor(26, 26, 46);
    pdf.text("Learning Assessment", margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);
    pdf.setFont("helvetica", "normal");

    const splitText = pdf.splitTextToSize(body.reportContent, contentWidth);
    pdf.text(splitText, margin, yPos);
    yPos += splitText.length * 5 + 5;

    // Notes Section
    if (body.notes) {
      if (yPos > 250) {
        pdf.addPage();
        yPos = 20;
      }

      pdf.setFontSize(14);
      pdf.setTextColor(26, 26, 46);
      pdf.text("Additional Notes", margin, yPos);
      yPos += 10;

      pdf.setFontSize(10);
      pdf.setTextColor(60, 60, 60);
      const notesSplit = pdf.splitTextToSize(body.notes, contentWidth);
      pdf.text(notesSplit, margin, yPos);
    }

    // Footer
    const pageCount = pdf.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Generated by Kernlo • kernlo.app`,
        pageWidth / 2,
        pdf.internal.pageSize.getHeight() - 8,
        { align: "center" }
      );
    }

    const pdfBuffer = Buffer.from(pdf.output("arraybuffer"));

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${body.childName}-progress-report.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF", details: String(error) },
      { status: 500 }
    );
  }
}
