import { NextRequest, NextResponse } from "next/server";

interface PDFRequest {
  childName: string;
  subject: string;
  activity: string;
  duration: string;
  notes: string;
  reportContent: string;
  generatedDate: string;
}

export async function POST(req: NextRequest) {
  try {
    const body: PDFRequest = await req.json();

    // Create HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              color: #1a1a1a;
              line-height: 1.6;
              padding: 0;
              margin: 0;
            }
            .container {
              width: 100%;
              max-width: 850px;
              padding: 40px;
              box-sizing: border-box;
              background: white;
            }
            .header {
              border-bottom: 2px solid #000;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              margin: 0;
              font-size: 24px;
              font-weight: 600;
            }
            .metadata {
              display: flex;
              justify-content: space-between;
              margin-top: 15px;
              font-size: 12px;
              color: #555;
            }
            .section {
              margin-bottom: 30px;
            }
            .section-title {
              font-size: 14px;
              font-weight: 600;
              margin-bottom: 12px;
              color: #000;
            }
            .activity-box {
              background: #f9f9f9;
              padding: 15px;
              border-radius: 4px;
              border: 1px solid #e5e5e5;
              font-size: 12px;
            }
            .activity-item {
              margin-bottom: 8px;
            }
            .label {
              font-weight: 600;
              color: #666;
              font-size: 11px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              display: inline-block;
              width: 80px;
            }
            .value {
              color: #1a1a1a;
            }
            .section-content {
              font-size: 12px;
              color: #333;
              line-height: 1.6;
              text-align: justify;
              white-space: pre-wrap;
              word-break: break-word;
            }
            .footer {
              margin-top: 40px;
              padding-top: 15px;
              border-top: 1px solid #ddd;
              font-size: 10px;
              color: #999;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Learning Progress Report</h1>
              <div class="metadata">
                <div><span class="label">Student:</span> <span class="value">${body.childName}</span></div>
                <div><span class="label">Date:</span> <span class="value">${body.generatedDate}</span></div>
              </div>
            </div>

            <div class="section">
              <div class="section-title">Activity Summary</div>
              <div class="activity-box">
                <div class="activity-item"><span class="label">Subject:</span> <span class="value">${body.subject}</span></div>
                <div class="activity-item"><span class="label">Activity:</span> <span class="value">${body.activity}</span></div>
                <div class="activity-item"><span class="label">Duration:</span> <span class="value">${body.duration} minutes</span></div>
                ${body.notes ? `<div class="activity-item"><span class="label">Notes:</span> <span class="value">${body.notes}</span></div>` : ""}
              </div>
            </div>

            <div class="section">
              <div class="section-title">Learning Assessment</div>
              <div class="section-content">${body.reportContent}</div>
            </div>

            <div class="footer">
              Generated by Kernlo • kernlo.app
            </div>
          </div>
        </body>
      </html>
    `;

    // For now, return HTML as downloadable file
    // In production, use a PDF library like puppeteer or similar
    return new NextResponse(htmlContent, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${body.childName}-progress-report.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    );
  }
}
