"use client";

import Link from "next/link";

const COLORS = {
  primary: "#0066cc",
  dark: "#1a1a2e",
  light: "#f0f7ff",
};

export default function PrivacyPage() {
  return (
    <main style={{ backgroundColor: COLORS.light }}>
      {/* Navigation */}
      <nav style={{ backgroundColor: "white", borderBottom: "1px solid #e5e7eb" }}>
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" style={{ color: COLORS.primary }} className="text-2xl font-bold">
            kernlo
          </Link>
          <Link
            href="/"
            style={{ color: COLORS.primary }}
            className="text-sm font-medium hover:opacity-70"
          >
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 style={{ color: COLORS.dark }} className="text-4xl font-bold mb-8">
          Privacy Policy
        </h1>

        <div style={{ backgroundColor: "white", borderRadius: "12px" }} className="p-8 border border-gray-200 space-y-8">
          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              1. Introduction
            </h2>
            <p style={{ color: "#666" }} className="mb-4">
              Kernlo ("we," "us," "our") respects your privacy and is committed to protecting it. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website and application.
            </p>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              2. Information We Collect
            </h2>
            <p style={{ color: "#666" }} className="mb-4">We collect information you provide directly:</p>
            <ul style={{ color: "#666" }} className="list-disc list-inside space-y-2 ml-4">
              <li>Email address and password when you create an account</li>
              <li>Child names, ages, and grades you enter</li>
              <li>Activity logs (subjects, duration, platforms, notes)</li>
              <li>Reports generated by our AI system</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              3. How We Use Your Information
            </h2>
            <p style={{ color: "#666" }} className="mb-4">We use the information we collect to:</p>
            <ul style={{ color: "#666" }} className="list-disc list-inside space-y-2 ml-4">
              <li>Provide, operate, and maintain Kernlo</li>
              <li>Generate progress reports using AI</li>
              <li>Track your trial period and subscription status</li>
              <li>Improve our service and user experience</li>
              <li>Send service announcements and support messages</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              4. Data Security
            </h2>
            <p style={{ color: "#666" }} className="mb-4">
              We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.
            </p>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              5. Third-Party Services
            </h2>
            <p style={{ color: "#666" }} className="mb-4">
              We use third-party services for payment processing (Stripe), AI report generation (OpenAI), and hosting. These services have their own privacy policies, and we encourage you to review them.
            </p>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              6. Children's Privacy
            </h2>
            <p style={{ color: "#666" }} className="mb-4">
              Kernlo is designed for homeschool parents. We do not knowingly collect personal information from children under 13. Parents/guardians who provide child information are responsible for its accuracy.
            </p>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              7. Your Rights
            </h2>
            <p style={{ color: "#666" }} className="mb-4">You have the right to:</p>
            <ul style={{ color: "#666" }} className="list-disc list-inside space-y-2 ml-4">
              <li>Access the personal information we hold about you</li>
              <li>Request deletion of your account and data</li>
              <li>Export your data in a portable format</li>
              <li>Opt-out of non-essential communications</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: COLORS.dark }} className="text-2xl font-bold mb-4">
              8. Contact Us
            </h2>
            <p style={{ color: "#666" }} className="mb-4">
              If you have questions about this Privacy Policy or our privacy practices, contact us at:
            </p>
            <p style={{ color: COLORS.primary }} className="font-medium">
              hello@kernlo.app
            </p>
          </section>

          <section>
            <p style={{ color: "#999" }} className="text-sm">
              Last updated: April 12, 2026
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
