import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ReportData {
  childName: string;
  subject: string;
  activity: string;
  duration: string;
  notes: string;
  reportContent: string;
  generatedDate: string;
}

export async function generatePDF(data: ReportData): Promise<Blob> {
  // Create HTML template for the report
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
            color: #1a1a1a;
            line-height: 1.6;
            padding: 0;
            margin: 0;
          }
          .container {
            width: 8.5in;
            height: 11in;
            padding: 0.75in;
            box-sizing: border-box;
            background: white;
          }
          .header {
            border-bottom: 2px solid #000;
            padding-bottom: 0.5in;
            margin-bottom: 0.5in;
          }
          .header h1 {
            margin: 0;
            font-size: 20px;
            font-weight: 600;
          }
          .header p {
            margin: 0.25in 0 0 0;
            font-size: 11px;
            color: #666;
          }
          .metadata {
            display: flex;
            justify-content: space-between;
            margin-top: 0.3in;
            font-size: 11px;
            color: #555;
          }
          .section {
            margin-bottom: 0.5in;
          }
          .section-title {
            font-size: 13px;
            font-weight: 600;
            margin-bottom: 0.15in;
            color: #000;
          }
          .section-content {
            font-size: 11px;
            color: #333;
            line-height: 1.5;
          }
          .activity-box {
            background: #f9f9f9;
            padding: 0.25in;
            border-radius: 4px;
            margin-bottom: 0.25in;
            font-size: 11px;
          }
          .label {
            font-weight: 600;
            color: #555;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .value {
            color: #1a1a1a;
            margin-top: 0.1in;
          }
          .footer {
            position: absolute;
            bottom: 0.5in;
            left: 0.75in;
            right: 0.75in;
            font-size: 9px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 0.2in;
          }
          .report-text {
            white-space: pre-wrap;
            word-break: break-word;
            font-size: 11px;
            line-height: 1.6;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Learning Progress Report</h1>
            <div class="metadata">
              <div><span class="label">Student:</span> <span class="value">${data.childName}</span></div>
              <div><span class="label">Date:</span> <span class="value">${data.generatedDate}</span></div>
            </div>
          </div>

          <div class="section">
            <div class="section-title">Activity Summary</div>
            <div class="activity-box">
              <div><span class="label">Subject:</span> <span class="value">${data.subject}</span></div>
              <div style="margin-top: 0.1in;"><span class="label">Activity:</span> <span class="value">${data.activity}</span></div>
              <div style="margin-top: 0.1in;"><span class="label">Duration:</span> <span class="value">${data.duration} minutes</span></div>
              ${data.notes ? `<div style="margin-top: 0.1in;"><span class="label">Notes:</span> <span class="value">${data.notes}</span></div>` : ""}
            </div>
          </div>

          <div class="section">
            <div class="section-title">Learning Assessment</div>
            <div class="section-content">
              <div class="report-text">${data.reportContent}</div>
            </div>
          </div>

          <div class="footer">
            Generated by Kernlo • kernlo.app
          </div>
        </div>
      </body>
    </html>
  `;

  // Convert HTML to canvas
  // Create a temporary element to hold the HTML
  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = htmlContent;
  document.body.appendChild(tempDiv);

  const canvas = await html2canvas(tempDiv, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
  });

  document.body.removeChild(tempDiv);

  // Create PDF from canvas
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "in",
    format: "letter",
  });

  const imgData = canvas.toDataURL("image/png");
  pdf.addImage(imgData, "PNG", 0, 0, 8.5, 11);

  return pdf.output("blob");
}
